### PR TITLE
Rating

### LINKED ISSUE #84: Front-end of rating in the feed, in a post, and in a search
As part of #2, it will be possible for the user to see the rating of a conference.

### PR DESCRIPTION
**Pull request by TiagooGomess**
The back-end is also implemented.

Screenshot from 2020-11-27 12-36-43

Screenshot from 2020-11-27 12-36-22

### CODE REVIEW

**Review by 2dukes — COMMENTED** [review]
What about when a rating has decimals like 4.3?

**Comment by TiagooGomess** [comment]
> What about when a rating has decimals like 4.3?

It appears 4.3

**Comment by TiagooGomess** [comment]
> What about when a rating has decimals like 4.3?
Solved :) 
Screenshot from 2020-11-27 12-51-43

**Review by 2dukes — APPROVED** [review]
Alright, nice! :+1:

**Pull request merged**
