### PR TITLE
Merge feed explore

### LINKED ISSUE #109: Merge explore and feed screens
As part of #14, #13, #12, #11 we want to give the user the option to search for conferences. Since there's a lot of overlap of functionality between the explore and feed screens, it makes sense to merge them.

### LINKED ISSUE #145: Add app logo on the top left corner
Add an image of the app's logo on the top left corner.

### PR DESCRIPTION
**Pull request by TiagooGomess**
Screenshot_2020-12-06-13-11-21-516_com example ESOF

### CODE REVIEW

**Review by matosjoaops — APPROVED** [review]

**Comment by 2dukes** [comment]
When you press Enter it drops this error:
Screenshot from 2020-12-06 19-40-43

**Comment by TiagooGomess** [comment]
@2dukes @TitanicThompson1 @Jumaruba I need help to put the query results in the lists `conferences` and `conferencesRef`. The code I've tried is commented between lines 71 and 87.

**Comment by 2dukes** [comment]
Bug seems solved. Please confirm what I'm saying :smile:

**Comment by TiagooGomess** [comment]
Thanks!!

**Pull request merged**
